# Generated by Django 3.2.9 on 2022-07-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=70)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('direction', models.CharField(blank=True, max_length=90, verbose_name=' ')),
                ('bio', models.TextField(blank=True, max_length=400)),
                ('address', models.CharField(blank=True, max_length=80)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Users profile',
            },
        ),
    ]
