# Generated by Django 3.2.9 on 2022-07-23 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_project_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to=settings.AUTH_USER_MODEL),
        ),
    ]
