# Generated by Django 3.2.9 on 2022-07-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_skill_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_softskill',
            field=models.BooleanField(default=False),
        ),
    ]
