# Generated by Django 4.0.6 on 2022-07-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/IMG_20220114_104710_103.JPG', upload_to='avatars/'),
        ),
    ]
