# Generated by Django 4.0.6 on 2022-07-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='is_softskill',
            field=models.BooleanField(help_text='Is softskill?'),
        ),
    ]
