# Generated by Django 4.0.6 on 2022-07-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_tag_project_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
